# Generated by Django 3.2.7 on 2021-09-17 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inside_Products_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('video_file', models.FileField(null=True, upload_to='')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.products')),
            ],
        ),
        migrations.CreateModel(
            name='Inside_Products_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.products')),
            ],
        ),
    ]
