# Generated by Django 3.2.7 on 2021-09-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_inside_products_file_inside_products_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='inside_products_file',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='inside_products_file',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.DeleteModel(
            name='Inside_Products_Video',
        ),
    ]
