# Generated by Django 3.2.7 on 2021-09-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210917_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='inside_products_file',
            name='image',
            field=models.ImageField(blank=True, default='images/favicon.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inside_products_file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='inside_products_file',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
