# Generated by Django 3.2.7 on 2021-09-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210918_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inside_products_file',
            name='image',
            field=models.ImageField(blank=True, default='static/images/favicon.png', null=True, upload_to=''),
        ),
    ]
