# Generated by Django 3.2.7 on 2021-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_inside_products_file_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inside_products_file',
            name='image',
            field=models.ImageField(blank=True, default='favicon.png', null=True, upload_to=''),
        ),
    ]
